version: "3.9"

services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7
    ports:
      - "6379:6379"
